CREATE DATABASE IF NOT EXISTS skillSwapPlatform;
USE skillSwapPlatform;

CREATE TABLE users (
id INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
PASSWORD VARCHAR(255) NOT NULL,
major VARCHAR(100),
bio TEXT,
profilePicture VARCHAR(255),
reputationScore DECIMAL(3,2) DEFAULT 0,
STATUS ENUM('active', 'suspended') DEFAULT 'active',
is_verified TINYINT(1) DEFAULT 0,
verification_code VARCHAR(10) NULL,
create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);
DESC users;

CREATE TABLE categories (
id INT AUTO_INCREMENT PRIMARY KEY,
categoryName VARCHAR(100) NOT NULL UNIQUE
);
DESC categories;

CREATE TABLE skills (
id INT AUTO_INCREMENT PRIMARY KEY,
userId INT NOT NULL,
categoryId INT NOT NULL,
skillName VARCHAR(100) NOT NULL,
description TEXT,
skillLevel ENUM('Beginner', 'Intermediate', 'Advanced', 'Master'),
create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (categoryId) REFERENCES categories(id) ON DELETE CASCADE ON UPDATE CASCADE
);
DESC skills;

CREATE TABLE collaborationRequests (
id INT AUTO_INCREMENT PRIMARY KEY,
senderId INT NOT NULL,
receiverId INT NOT NULL,
message TEXT,
STATUS ENUM('pending', 'accepted', 'rejected', 'completed') DEFAULT 'pending',
create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (senderId) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (receiverId) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);
DESC collaborationRequests;

CREATE TABLE reviews (
id INT AUTO_INCREMENT PRIMARY KEY,
collaborationId INT NOT NULL,
reviewerId INT NOT NULL,
reviewedUserId INT NOT NULL,
rating SMALLINT NOT NULL CHECK (rating >= 1 AND rating <= 5),
COMMENT TEXT,
create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (collaborationId) REFERENCES collaborationRequests(id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (reviewerId) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (reviewedUserId) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);
DESC reviews;

CREATE TABLE admins (
id INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
PASSWORD VARCHAR(255) NOT NULL,
create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
DESC admins;

CREATE TABLE reports (
id INT AUTO_INCREMENT PRIMARY KEY,
handledByAdminId INT NOT NULL,
reporterId INT NOT NULL,
reportedUserId INT NOT NULL,
reason TEXT NOT NULL,
STATUS ENUM('pending', 'resolved', 'rejected') DEFAULT 'pending',
create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (handledByAdminId) REFERENCES admins(id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (reporterId) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (reportedUserId) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);
DESC reports;

